[tool.poetry]
name = "s2_indices"
version = "1.0.6"
description = "Create Docker image with dependencies and indices definitions. "
authors = ["ValentinaHutter <valentina.hutter@eodc.eu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.11"
tornado =  "6.1"
fsspec = "2025.2.0"
cloudpickle = "2.2.0"
msgpack = "1.0.4"
toolz = "0.12.0"
pystac = "1.12.2"
pystac-client = "0.8.6"
numpy = "1.26.4"
netcdf4 = "1.7.2"
h5netcdf = "1.6.1"
scipy = "1.15.2"
shapely = "2.1.0"
rasterio = {extras = ["core", "s3"], version = "1.4.3"}
odc-geo = "0.4.10"
odc-stac = "0.3.3"
pandas = "2.2.3"
pyproj = "3.7.1"
requests = "2.32.3"
zarr = "2.18.3"
xarray = "2025.1.2"
s3fs = "2025.2.0"
dask = {extras = ["array", "core", "distributed"], version = "2022.10.2"}
dask-gateway = ">=2025.4.0"
botocore = "1.35.88"
boto3 = "1.35.88"
aiobotocore = "2.17.0"
aiohttp = "3.11.16"
numcodecs = "0.13.1"
bokeh = ">=3,<3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
